apiVersion: v1
kind: Pod
metadata:
  name: test-system-pod
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: test-container
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'System pod running'; sleep 30; done"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
