# Server configuration
write-kubeconfig-mode: "0644"
#tls-san:
#- "whistlekube.local"

cluster-init: true
 
# Disable addons we don't need
disable:
  - traefik
  - servicelb
#  - coredns
#  - local-storage
#  - metrics-server
flannel-backend: none
disable-network-policy: true
disable-kube-proxy: true
disable-cloud-controller: true
disable-helm-controller: true
